#! /bin/sh

sxhkd &
hsetroot -solid "#434C5E" &
xrdb -merge $HOME/.Xresources &
polybar nord &
setxkbmap -option caps:swapescape &
xset r rate 250 75 &

bspc monitor -d 1 2 3 4

bspc config border_width         4
bspc config window_gap          66
bspc config active_border_color "#BF616A"
bspc config normal_border_color "#BF616A"
bspc config focused_border_color "#A3BE8C"
bspc config presel_border_color "#BF616A"
bspc config urgent_border_color "#BF616A"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

